name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Update README.md
      run: |
          output=$(node index.js)
          sed -i "1i\\
          ${output}\\
          " README.md
          previous_output=$(cat previous_output.txt)
          sed -i "1,/${previous_output}/d" README.md
          echo "$output" > previous_output.txt
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '1023092893+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
