name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

jobs:
  run_node_and_insert_to_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run Node.js Script and Insert to README   # 运行 node index.js
        run: |
          output=$(node index.js)
          echo "${output}" | cat - README.md > README.md.tmp
          mv README.md.tmp README.md

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Insert Node.js script output to README"
          git push
